GET  https://localhost:5001/game HTTP/1.1
###
POST https://localhost:5001/game HTTP/1.1
content-type: application/json
###
GET  https://localhost:5001/game/28ee26a8-9a95-4e96-a4cf-2f43a668f719 HTTP/1.1
###
POST  https://localhost:5001/game/28ee26a8-9a95-4e96-a4cf-2f43a668f719/play HTTP/1.1
Content-Type: application/x-www-form-urlencoded

playerName=JaniHyytiainen
###
POST  https://localhost:5001/game/28ee26a8-9a95-4e96-a4cf-2f43a668f719/challenge HTTP/1.1
Content-Type: application/x-www-form-urlencoded

challengerName=JohnDoe
###
POST  https://localhost:5001/game/28ee26a8-9a95-4e96-a4cf-2f43a668f719/play/Rock HTTP/1.1
Content-Type: application/json
###
POST  https://localhost:5001/game/28ee26a8-9a95-4e96-a4cf-2f43a668f719/challenge/Paper HTTP/1.1
Content-Type: application/json
###

